general:
  seed: 1
  num_workers: 0

data:
  dataset_name: AID1798
  root: ./datasets
  split_scheme: random_cv1
  mol_repr: 2d_graph
  one_hot: false

train:
  num_epochs: 50
  batch_size: 128
  warmup_percentage: 0.1
  peak_lr: 1e-3
  end_lr: 1e-4
  weight_decay: 0.01
  early_stop: 50